from django.db import models

from uuid import uuid4
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


def deserialize_user(user):
    """Deserialize user instance to JSON."""
    return {
        'id': user.id,
        'username': user.username,
        'email': user.email,
        'first_name': user.first_name,
        'last_name': user.last_name,
    }


def _generate_unique_uri():
    """Generate a unique uri for a chat session."""
    return str(uuid4()).replace("-", "")[:15]


class TrackableDateModel(models.Model):
    """Abstract model to track the creation/update date for a model."""

    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class ChatSession(TrackableDateModel):
    """Chat Session.
    URI (Unique Resource Identifier) generated by taking
    the first 15 characters form a UUID
    """

    owner = models.ForeignKey(User, on_delete=models.PROTECT)
    uri = models.URLField(default=_generate_unique_uri)

    def __str__(self):
        return f"Chat session {self.uri}"


class ChatSessionMessage(TrackableDateModel):
    """Store messages for a session."""

    user = models.ForeignKey(User, on_delete=models.PROTECT)
    chat_session = models.ForeignKey(
        ChatSession,
        related_name='messages',
        on_delete=models.PROTECT
    )
    message = models.TextField(max_length=2000)

    def to_json(self):
        """Deserialize message instance to JSON."""
        return {
            'user': deserialize_user(self.user),
            'message': self.message,
            'created_at': self.create_date.isoformat(),
        }

    def __str__(self):
        return f"Message from {self.user.username} in {self.chat_session.uri}"


class ChatSessionParticipant(TrackableDateModel):
    """Store all users in a chat session."""

    chat_session = models.ForeignKey(
        ChatSession,
        related_name='participants',
        on_delete=models.PROTECT
    )
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.user.username} in {self.chat_session.uri}"